spring:
  flyway:
    schemas: smarthome
  application:
    name: smart-home-service
  mvc:
    servlet:
      path: /

server:
  port: 8080
  compression:
    enabled: true
    mime-types: "application/json"
