spring:
  profiles:
    active: dev
  flyway:
    validate-on-migrate: false
    locations: classpath:/db/migration/base
    placeholders:
      dbUser: docker_db_user
  datasource:
    username: docker_db_user
    url: jdbc:postgresql://localhost:5432/test?currentSchema=smarthome
    password: docker_db_user
    driver-class-name: org.postgresql.Driver

#application:
#  admin:
#    username: monitor
#    password: password

server:
  port:
    8080

logging:
  file:
    path: ${java.io.tmpdir}